### ISSUE TITLE
Symptoms checker

### ISSUE THREAD

**Issue by MohamedEl1** [manualzuru/FightPandemics.com#19]
- [x] Initial version is merged 

there is still some work to finish the whole flow (so feel free to assign yourself to do this):

- [ ] add results page based on answers
- [ ] adjust flow with questions for 1st or 3d person
- [ ] optimize data model ( does it need to be saved? Better use translation keys for additional logic and adding translations.

The code can also be optimized to more reusable React compoments for the StepWizard, as well as some finishing touches:

- [ ] fix complete flow => next and <= back
- [ ] allow to exit the wizard
- [ ] fine tune styling, fonts sizes etc.

**Comment by robinv85** [comment]
I think it has to be redone with the step wizard flow like need-help and offer-help

**Comment by Gtstride** [comment]
I did that already, but can't seem to push to the repos, without conflict

**Comment by robinv85** [comment]
So I'm working on this, reviewing what is done and will merge it properly to master
