### ISSUE TITLE
Running "docker-compose up" doesn't watch for file changes

### ISSUE THREAD

**Issue by anniegiang** [manualzuru/FightPandemics.com#43]
Right now I can't see file changes instantly when developing. 

To see changes I need to kill the server and rebuild using `docker-compose up --build`. 

Is there a way to have docker watch for file changes without rebuilding each time?

**Comment by neemiasjnr** [comment]
@anniegiang Good point, I created a production ready container so it won't watch for changes unfortunately. But it's possible to create a Dockerfile.dev and watch for changes, I'm gonna work on that today

**Comment by anniegiang** [comment]
@neemiasjnr sounds good!
