### ISSUE TITLE
Backend: upgrade to Fastify + tools for API schema documentation & validation

### ISSUE THREAD

**Issue by robinv85** [manualzuru/FightPandemics.com#56]
- [x] OpenAPI specs
- [x]  Swagger UI via docker
- [x]  Upgrade to Fastify (includes schema validation)
- [x]  nice to have: generate JSON schema's for validation from API specs from

**Comment by neemiasjnr** [comment]
Amazing bro

**Comment by robinv85** [comment]
Most of the work has been done, updating the API spec is pretty much "cointinuously" 
most important part right now I think is that the request validation schema's can be automatically generated
