### ISSUE TITLE
React failing to compile material ui icons

### ISSUE THREAD

**Issue by anniegiang** [manualzuru/FightPandemics.com#85]
I've tried npm install in client and docker rebuild but still run into this issue... For now I comment out that file where it imports it

<img width="962" alt="Screen Shot 2020-04-08 at 2 45 38 PM" src="https://user-images.githubusercontent.com/42228386/78836952-f7ac8780-79a7-11ea-96bd-a8f6b40b9c4c.png">

**Comment by robinv85** [comment]
Hmm @anniegiang is the module installed? Did you check package.json? 
Maybe try to install it again and check if  something was wrong with package or package-lock ... 
I've pulled latest master and besides a bunch of lint warnings it seems to work

**Comment by anniegiang** [comment]
The module is in client/package.json and I've tried npm install and rebuilding docker but no luck

**Comment by robinv85** [comment]
@anniegiang do you only run the react app from inside docker, or also locally with just running `npm start` from `./client` ?

**Comment by anniegiang** [comment]
normally I run `docker-compose up` from the root folder.  i can try just running the client if i'm working on frontend

**Comment by robinv85** [comment]
Yeah seems like the docker-compose file is broken because of change in PR #60 
Was trying to make it consistent use of quotes but forgot that YAML has different use for single / double quotes ... in many cases they can even be omitted so I'll make hotfix that hopefully fixes this.
